##  Plugin Information  ##
name: dejiplus
version: version-number-unknown
main: net.syamn.dejiplus.Dejiplus
description: Minecraft dejiplus server plugin
website: http://www.dejiplus.net/
softdepend: [Vault]
##  Original Author     ##
author: syam
commands:
    dejiplus:
      usage: /dejiplus - to see the help
      aliases: [deji]
      description: To see the plugin help.
permissions:
    dejiplus.user.dropspawner:
        default: op
        description: Can drop spawner
    dejiplus.admin.edititem:
        default: op
        description: Can use item edit command
    dejiplus.admin.reload:
        default: op
        description: Can use reload command